# Generated by Django 5.1.3 on 2024-11-13 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_assets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assets',
            new_name='Asset',
        ),
    ]
