# Generated by Django 5.1.3 on 2024-11-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_rename_assets_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='borrowed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='returned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
